version: "3"

services:
  proxy:
    build: ./services/proxy
    ports:
      - "8899:8899"
  client:
    build: ./services/client
    environment:
      HTTP_PROXY: "host.docker.internal:8899"
      HTTPS_PROXY: "host.docker.internal:8899"
      NO_PROXY: ""
    extra_hosts:
      - "host.docker.internal:host-gateway"
